### ISSUE TITLE
Problem with 'date -j' on Debian Jessie

### ISSUE THREAD

**Issue by achaussier** [markchalloner/git-semver#10]
Hello,

First, thanks for the share.

With the resolution of #9 with d16599d44516d42c57a1a1f407fd93d3f2cf6ffd, I have an error due to -j option (not exists in Jessie) :

```
 ~  dev  git-semver   master  ✔  00:19:41  130  git semver get
date : option invalide -- 'j'
Saisissez « date --help » pour plus d'informations.
date : option invalide -- 'j'
Saisissez « date --help » pour plus d'informations.
/usr/local/bin/git-semver: ligne 185 : [: -86400 : opérateur unaire attendu
2.0.2
```

Perhaps it should be useful to add a ondition to choice the proper date syntax, based on date version or OS family/distribution ?

For information :
- date version on Jessie :  'date (GNU coreutils) 8.23'
- I've disable updates to avoid the problem :)

**Comment by arghasen** [comment]
Same issue is on Mac OSX El Capitan

**Comment by x3ro** [comment]
:+1:

**Comment by aguegu** [comment]
same problem on ubuntu. 

The quick fix would be disabling the auto update. 

@markchalloner I wonder what your develop environment is.

**Comment by markchalloner** [comment]
@arghasen, have you installed homebrew coreutils by any chance? What is your output from `date --version`?

**Comment by markchalloner** [comment]
Commit fd76272 should fix this issue. Test by:
- update clone: `cd {git-semver dir} && git checkout master && git pull`
- force update checks: set `UPDATE_CHECK_FORCE=1` in `~/.git-semver/config`
- run git semver get: `git semver get`

```
$ git semver get
Warning: Forcing update check (UPDATE_CHECK_FORCE=1)
New version 2.0.2 found. Update (y/n)? (defaults to "y"): n
2.0.2
```

**Comment by arghasen** [comment]
Looks good Mark. A couple of new warnings are up though
Arghas-MacBook-Pro% git semver get
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
/usr/local/bin/git-semver: line 188: 2016-05-03: command not found
/usr/local/bin/git-semver: line 201: 2016-05-03: command not found
/usr/local/bin/git-semver: line 205: [: -86400: unary operator expected
2.0.2

**Comment by arghasen** [comment]
I had home-brew coreutils earlier but now I am using the stock date from OSX

**Comment by markchalloner** [comment]
Thanks should be fixed on master
