### ISSUE TITLE
two questions ...

### ISSUE THREAD

**Issue by sunnysideup** [markchalloner/git-semver#22]
Hi,

Just wondering if anyone is working on

(a)  a system that automagically works out if a tag is MAJOR / MINOR / PATCH based on the commit message

(b) adding `git push --tags` to the end of the script

Let me know where we can help - if not.

Thank you

Nicolaas
PS awesome module

**Comment by markchalloner** [comment]
Hi Nicolas,

I'm afraid I don't have the time to add new features, however, if you open a pull request I'll happily review with a view to merging and tagging a new version.

Regards
Mark

**Comment by sunnysideup** [comment]
Hi Mark,

Thank you for your reply. 

Are these good ideas at all?  

git push --tags should be easy, but may be controversial.

automatigically adding a new tag would be awesome, especially if you can set your own keywords for commit messages.

I will have a look.

Thank you again

**Comment by markchalloner** [comment]
> automatigically adding a new tag would be awesome, especially if you can set your own keywords for commit messages.

I don't think this would be possible in this project, however there's nothing to stop you adding a [post-commit hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks#_committing_workflow_hooks) that parses the commit message for a bump (e.g. `#major`) and subsequently calls `git semver`. You might want to check out [`icefox/git-hooks`](https://github.com/icefox/git-hooks) or the newer [`git-hooks/git-hooks`](https://github.com/git-hooks/git-hooks) to version control that.

> git push --tags should be easy, but may be controversial.

I agree. It sounds like a useful feature to have but I suggest this should be dependent on [config](https://github.com/markchalloner/git-semver/blob/3b09567f3a4995f5b9012a805e3c8df7f41b7d5f/config.example) and default to off. 

Alternatively this could be done in the same post-commit hook as above.
