### ISSUE TITLE
Rollback after accidental increase

### ISSUE THREAD

**Issue by stokerd** [markchalloner/git-semver#34]
I was attempting to check the tag: `git semver minor --dryrun` however I forget to add the `--dryrun` and it incremented my minor version. How do I roll the tag back? I did not yet push the tags using `git push -tags`, this is all still local to my machine.

Thanks!

**Comment by markchalloner** [comment]
@stokerd `git-semver` only adds a tag which can be deleted with `git tag -d <version>`.
