### ISSUE TITLE
Consider prefixing tags with "v"

### ISSUE THREAD

**Issue by davvid** [markchalloner/git-semver#5]
Tags should be named `v1.2.3`, etc.  This is the tagging scheme used by Git and the kernel itself.  It's best when everyone uses the same convention.

**Comment by markchalloner** [comment]
Thanks @davvid. Definitely an option I'ld like to include. I'll have a think about how best to do this.

**Comment by davvid** [comment]
This option should be the default behavior.  Just saying.. it seems like the current behavior should be the optional thing for a user who wants the "Git Semver".
